[package]
name = "pratt-rust"
version = "0.1.0"
authors = ["Jack Clarke <me@jackclarke.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
